k = size( pgi1Rec, 2 );

figure();
subplot( 3, 1 ,1 ); 
hold on; grid on; title(' Position '); ylabel(' m ');
plot( dpgiRec(1,1:k), 'r' );
plot( dpgiRec(2,1:k), 'g' );
plot( dpgiRec(3,1:k), 'b' );
hold off;
subplot( 3, 1 ,2 ); 
hold on; grid on; title(' Attitude '); ylabel(' deg ');
plot( dthgiRec(1,1:k)*180/pi, 'r' );
plot( dthgiRec(2,1:k)*180/pi, 'g' );
plot( dthgiRec(3,1:k)*180/pi, 'b' );
hold off;
subplot( 3, 1 ,3 ); 
hold on; grid on; title(' Velocity '); ylabel(' m/s ');
plot( dvgiRec(1,1:k), 'r' );
plot( dvgiRec(2,1:k), 'g' );
plot( dvgiRec(3,1:k), 'b' );
hold off;

figure();
subplot( 2, 1 ,1 ); 
hold on; grid on; title(' Acc bias '); ylabel(' m/s^2 ');
plot( dbaRec(1,1:k), 'r' );
plot( dbaRec(2,1:k), 'g' );
plot( dbaRec(3,1:k), 'b' );
hold off;
subplot( 2, 1 ,2 ); 
hold on; grid on; title(' Gyro bias '); ylabel(' deg/s ');
plot( dbgRec(1,1:k)*180/pi, 'r' );
plot( dbgRec(2,1:k)*180/pi, 'g' );
plot( dbgRec(3,1:k)*180/pi, 'b' );
hold off;

figure();
subplot( 4, 1 ,1 ); 
hold on; grid on; title(' Position '); ylabel(' m ');
plot( dpgi1Rec(1,1:k), 'r' );
plot( dpgi1Rec(2,1:k), 'g' );
plot( dpgi1Rec(3,1:k), 'b' );
hold off;
subplot( 4, 1 ,2 ); 
hold on; grid on; title(' Attitude '); ylabel(' deg ');
plot( dthgi1Rec(1,1:k)*180/pi, 'r' );
plot( dthgi1Rec(2,1:k)*180/pi, 'g' );
plot( dthgi1Rec(3,1:k)*180/pi, 'b' );
hold off;
subplot( 4, 1 ,3 ); 
hold on; grid on; title(' Position '); ylabel(' m ');
plot( dpgi2Rec(1,1:k), 'r' );
plot( dpgi2Rec(2,1:k), 'g' );
plot( dpgi2Rec(3,1:k), 'b' );
hold off;
subplot( 4, 1 ,4 ); 
hold on; grid on; title(' Attitude '); ylabel(' deg ');
plot( dthgi2Rec(1,1:k)*180/pi, 'r' );
plot( dthgi2Rec(2,1:k)*180/pi, 'g' );
plot( dthgi2Rec(3,1:k)*180/pi, 'b' );
hold off;          
