k = size( pgi1Rec, 2 );

figure();
subplot( 3, 1 ,1 ); 
hold on; grid on; title(' Position '); ylabel(' m ');
plot( pgiRec(1,1:k), 'r' );
plot( pgiRec(2,1:k), 'g' );
plot( pgiRec(3,1:k), 'b' );
hold off;
subplot( 3, 1 ,2 ); 
hold on; grid on; title(' Attitude '); ylabel(' deg ');
plot( qgiRec(1,1:k)*180/pi, 'r' );
plot( qgiRec(2,1:k)*180/pi, 'g' );
plot( qgiRec(3,1:k)*180/pi, 'b' );
hold off;
subplot( 3, 1 ,3 ); 
hold on; grid on; title(' Velocity '); ylabel(' m/s ');
plot( vgiRec(1,1:k), 'r' );
plot( vgiRec(2,1:k), 'g' );
plot( vgiRec(3,1:k), 'b' );
hold off;

figure();
subplot( 2, 1 ,1 ); 
hold on; grid on; title(' Acc bias '); ylabel(' m/s^2 ');
plot( baRec(1,1:k), 'r' );
plot( baRec(2,1:k), 'g' );
plot( baRec(3,1:k), 'b' );
hold off;
subplot( 2, 1 ,2 ); 
hold on; grid on; title(' Gyro bias '); ylabel(' deg/s ');
plot( bgRec(1,1:k)*180/pi, 'r' );
plot( bgRec(2,1:k)*180/pi, 'g' );
plot( bgRec(3,1:k)*180/pi, 'b' );
hold off;

figure();
subplot( 4, 1 ,1 ); 
hold on; grid on; title(' Position '); ylabel(' m ');
plot( pgi1Rec(1,1:k), 'r' );
plot( pgi1Rec(2,1:k), 'g' );
plot( pgi1Rec(3,1:k), 'b' );
hold off;
subplot( 4, 1 ,2 ); 
hold on; grid on; title(' Attitude '); ylabel(' deg ');
plot( qgi1Rec(1,1:k)*180/pi, 'r' );
plot( qgi1Rec(2,1:k)*180/pi, 'g' );
plot( qgi1Rec(3,1:k)*180/pi, 'b' );
hold off;

subplot( 4, 1 ,3 ); 
hold on; grid on; title(' Position '); ylabel(' m ');
plot( pgi2Rec(1,1:k), 'r' );
plot( pgi2Rec(2,1:k), 'g' );
plot( pgi2Rec(3,1:k), 'b' );
hold off;
subplot( 4, 1 ,4 ); 
hold on; grid on; title(' Attitude '); ylabel(' deg ');
plot( pgi2Rec(1,1:k), 'r' );
plot( pgi2Rec(2,1:k), 'g' );
plot( qgi2Rec(3,1:k), 'b' );
hold off;         