k = size( pgi1Rec, 2 );

figure();
subplot( 3, 1 ,1 ); 
hold on; grid on; title(' Position '); ylabel(' m ');
plot( 3*std_pgiRec(1,1:k), 'r' ); plot( -3*std_pgiRec(1,1:k), 'r' );
plot( 3*std_pgiRec(2,1:k), 'g' ); plot( -3*std_pgiRec(2,1:k), 'g' );
plot( 3*std_pgiRec(3,1:k), 'b' ); plot( -3*std_pgiRec(3,1:k), 'b' );
hold off;
subplot( 3, 1 ,2 ); 
hold on; grid on; title(' Attitude '); ylabel(' deg ');
plot( 3*std_thgiRec(1,1:k)*180/pi, 'r' ); plot( -3*std_thgiRec(1,1:k)*180/pi, 'r' );
plot( 3*std_thgiRec(2,1:k)*180/pi, 'g' ); plot( -3*std_thgiRec(2,1:k)*180/pi, 'g' );
plot( 3*std_thgiRec(3,1:k)*180/pi, 'b' ); plot( -3*std_thgiRec(3,1:k)*180/pi, 'b' );
hold off;
subplot( 3, 1 ,3 ); 
hold on; grid on; title(' Velocity '); ylabel(' m/s ');
plot( 3*std_vgiRec(1,1:k), 'r' ); plot( -3*std_vgiRec(1,1:k), 'r' );
plot( 3*std_vgiRec(2,1:k), 'g' ); plot( -3*std_vgiRec(2,1:k), 'g' );
plot( 3*std_vgiRec(3,1:k), 'b' ); plot( -3*std_vgiRec(3,1:k), 'b' );
hold off;

figure();
subplot( 2, 1 ,1 ); 
hold on; grid on; title(' Acc bias '); ylabel(' m/s^2 ');
plot( 3*std_baRec(1,1:k), 'r' ); plot( -3*std_baRec(1,1:k), 'r' );
plot( 3*std_baRec(2,1:k), 'g' ); plot( -3*std_baRec(2,1:k), 'g' );
plot( 3*std_baRec(3,1:k), 'b' ); plot( -3*std_baRec(3,1:k), 'b' );
hold off;
subplot( 2, 1 ,2 ); 
hold on; grid on; title(' Gyro bias '); ylabel(' deg/s ');
plot( 3*std_bgRec(1,1:k)*180/pi, 'r' ); plot( -3*std_bgRec(1,1:k)*180/pi, 'r' );
plot( 3*std_bgRec(2,1:k)*180/pi, 'g' ); plot( -3*std_bgRec(2,1:k)*180/pi, 'g' );
plot( 3*std_bgRec(3,1:k)*180/pi, 'b' ); plot( -3*std_bgRec(3,1:k)*180/pi, 'b' );
hold off;

figure();
subplot( 4, 1 ,1 ); 
hold on; grid on; title(' Position '); ylabel(' m ');
plot( 3*std_pgi1Rec(1,1:k), 'r' ); plot( -3*std_pgi1Rec(1,1:k), 'r' );
plot( 3*std_pgi1Rec(2,1:k), 'g' ); plot( -3*std_pgi1Rec(2,1:k), 'g' );
plot( 3*std_pgi1Rec(3,1:k), 'b' ); plot( -3*std_pgi1Rec(3,1:k), 'b' );
hold off;
subplot( 4, 1 ,2 ); 
hold on; grid on; title(' Attitude '); ylabel(' deg ');
plot( 3*std_thgi1Rec(1,1:k)*180/pi, 'r' ); plot( -3*std_thgi1Rec(1,1:k)*180/pi, 'r' );
plot( 3*std_thgi1Rec(2,1:k)*180/pi, 'g' ); plot( -3*std_thgi1Rec(2,1:k)*180/pi, 'g' );
plot( 3*std_thgi1Rec(3,1:k)*180/pi, 'b' ); plot( -3*std_thgi1Rec(3,1:k)*180/pi, 'b' );
hold off;
subplot( 4, 1 ,3 ); 
hold on; grid on; title(' Position '); ylabel(' m ');
plot( 3*std_pgi2Rec(1,1:k), 'r' ); plot( -3*std_pgi2Rec(1,1:k), 'r' );
plot( 3*std_pgi2Rec(2,1:k), 'g' ); plot( -3*std_pgi2Rec(2,1:k), 'g' );
plot( 3*std_pgi2Rec(3,1:k), 'b' ); plot( -3*std_pgi2Rec(3,1:k), 'b' );
hold off;
subplot( 4, 1 ,4 ); 
hold on; grid on; title(' Attitude '); ylabel(' deg ');
plot( 3*std_thgi2Rec(1,1:k)*180/pi, 'r' ); plot( -3*std_thgi2Rec(1,1:k)*180/pi, 'r' );
plot( 3*std_thgi2Rec(2,1:k)*180/pi, 'g' ); plot( -3*std_thgi2Rec(2,1:k)*180/pi, 'g' );
plot( 3*std_thgi2Rec(3,1:k)*180/pi, 'b' ); plot( -3*std_thgi2Rec(3,1:k)*180/pi, 'b' );
hold off;